### ISSUE TITLE
Jon Seddon's PRIMAVERA tables: various issues

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#162]
Hi all,

I am going to use this issue to address all the  problems we encounter with Jon Seddon's tables.

after the last commit (https://github.com/goord/ece2cmor3/commit/aad5405b9f447568b55c200d877fe3ece40ea067)  unfortunately ece2cmor3 with PRIMAVERA tables are longer working: I am using the most recent version of the tables (https://github.com/jonseddon/cmip6-cmor-tables/tree/master/Tables).
Here below the log file: there is a lot off errors like this one.
I will try later on to isolate the variable causing the error.
Thanks,
Paolo

`````
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/postproc.py", line 162, in cdo_worker
    if sum(map(lambda fname: os.path.getsize(fname), [f for f in files if os.path.exists(f)])) < maxsize:
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
````

**Comment by goord** [comment]
Hi Paolo, not sure whether the issue here is the primavera cmor tables... Can you attach the entire output?

**Comment by goord** [comment]
Hi Paolo, can you confirm that you are doing a single primavera job, with no concurrent jobs running? The problem may be that multiple ece2cmor jobs are writing to the same tempdir (if you don't specify this in the script it chooses /tmp/ece2cmor3) with all kind of weird errors as a consequence.

**Comment by goord** [comment]
Hi Paolo, I have run your setup myself and get the same problem, will investigate further

**Comment by goord** [comment]
Ok I think I fixed the problems, I added added proper handling of maxima and minima on sub-daily intervals

**Comment by oloapinivad** [comment]
Hi Gijs, sorry for the late reply, I am out for a training course in these days.
I can confirm that the problem is on a single job. I have just run with the most recent commit but I am still having the same issues. Did you committed the last changes? 
Thanks (as always!)
Ciao

**Comment by goord** [comment]
Sorry, forgot to push to the repo... here it is

**Comment by oloapinivad** [comment]
It works, thanks. 
I keep here the issue for further problem with these tables

**Comment by oloapinivad** [comment]
Hi, with some Omon variables the cmorization now crashes reporting: 

`````
^[[2;31;47mC Traceback:
! In function: cmor_variable
! ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'thetaoga' (table Omon)  with 2 dimensions, when it should have 1
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

Traceback (most recent call last):
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 111, in <module>
    main()
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 103, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 89, in execute
    execute_netcdf_task(dataset, task)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 128, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 172, in create_cmor_variable
    original_name=str(srcvar))
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 536, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

This occurs with **masso, volo, thetaoga** vars at least.

**Comment by goord** [comment]
Hi Paolo, I will have a look at this tomorrow.
