### ISSUE TITLE
Problem with some of the Eyr variables

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#836]
I asked NSC to publish some DECK experiments that I did with the OptimESM model configuration. NSC did run nctxck and found errors with these variables:

Eyr fracLut
Eyr cLitterLut
Eyr cSoilLut
Eyr cSoil
Eyr cVeg
Eyr cProduct
Eyr cProductLut
Eyr cVegLut
Eyr cLitter

All these are from Eyr, and the problem seems to be that they should be instantaneous, not time averages over the year, e.g.
````
fracLut:comment = "End of year values (not annual mean);...
````
Instantaneous variables should have no ``time_bnds``, and the time axis should be ``yrPt``

How does this look like in the LPJ-Guess output?
And can the time axis be fixed in ece2cmor3? 

NB: not all variables from Eyr are instantanous, some are time means (e.g. ``cLandYr``). And I'm not sure what should be the  correct date for the instantaneous variables: mid-year, end-of-year, Jan 1 ?

**Comment by nierad** [comment]
Thanks @klauswyser , I am looking into it

**Comment by nierad** [comment]
Thanks @klauswyser , I am looking into it

**Comment by nierad** [comment]
Hi @klauswyser:
Is it correct that the only reason they got rejected was the existing time_bnds parameter? We have cmorized e.g. cVeg in the past without an issue as far as I remember. 
I will see if I can quickly change the axis but am travelling all day today and don't have access to our output.

**Comment by klauswyser** [comment]
I don't recall, did you ever generate the variables in Eyr? Some variables exist both as monthly mean and yearly, e,g, [cVeg](https://clipc-services.ceda.ac.uk/dreq/u/3434c274f8ad8754f594d2b23c2d37db.html) Obviosuly the time axis is different in these.

And no, it's not just time_bnds that throws an error, here is the full list:
````
        Status: Error 001 -- Incorrect time axis over one or several time steps 
        Status: Error 004 -- Incorrect time bounds over one or several time steps 
        Status: Error 010b -- Start date in file is later than start date from filename 
        Status: Error 007b -- End date in file is late than end date from filename 
        Status: Error 009b -- End date in file is later than theoretical end date 
        Status: Error 002 -- An instantaneous time axis should not embed time boundaries
````
Most likely all these are addressed if the time axis and time stamp are set correctly which would be an issue mainly for ece2cmor. But it's good if alos LPJ-Guess folks have a look at it.

**Comment by nierad** [comment]
I just checked, you're right, we never did that.
Well, I think I have a fix, but I need to test it. @klauswyser, could you provide one cmorized file (cVeg) on Tetralith?

**Comment by klauswyser** [comment]
Here are a monthly and a yearly file: /nobackup/rossby27/proj/optimesm/sm_wyser/ece-run/CD45/output/lpjg/001/cVeg_*

**Comment by nierad** [comment]
Thanks, 
but I would like to have a cmorized file to compare.

**Comment by klauswyser** [comment]
Sorry. Here we go: /nobackup/rossby27/proj/optimesm/cmorized/CD45-0/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-ESM-1/piControl/r1i1p1f1/Eyr/cVeg/gr/v20240925/cVeg_Eyr_EC-Earth3-ESM-1_piControl_r1i1p1f1_gr_1850-1850.nc

**Comment by etiennesky** [comment]
if all e have are monthly means, then don't have the instantaneous value then we shouldn't be outputing it...   this is why we added the variables cLand1st and cLandYr to make sure we got the instantaneous values on Jan 1st.

**Comment by treerink** [comment]
I juste checked all the mentioned Eyr variables in the (OptimESM adjusted) Eyr table and there all info seems right for all these variables: 

- "frequency":  `YrPt`, 
- "cell_methods": "area: mean where land `time: point`",  
- "dimensions": "longitude latitude `time1`",

Not clear to me where things go wrong yet, but I understand @nierad does?

**Comment by klauswyser** [comment]
I just had a closer look at one of the variables, ``fracLut``, and its ``time`` dimension contains ``time_bnds`` which doesn't make sense for instantaneous values. And the dimension is not ``time1`` but ``time``, but I cannot tell if that's important. 
````
netcdf fracLut_Eyr_EC-Earth3-ESM-1_piControl_r1i1p1f1_gr_1850-1850 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        landuse = 4 ;
        lat = 256 ;
        lon = 512 ;
        bnds = 2 ;
        strlen = 26 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:units = "days since 1850-01-01" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
        double time_bnds(time, bnds) ;
[...]
````

**Comment by nierad** [comment]
@klauswyser: Yes, the error is in lpjg2cmor and it as mentioned, I might have a fix which I haven't had time to implement. Will see if I can get there tomorrow.

**Comment by nierad** [comment]
Happy new year @klauswyser and everyone! 
I have fixed the `time_bnd` issue for all variables using the "time1" temporal dimension (the ones mentioned above). Of course, the time dimension is still called "time" in the netCDF files. I have further set all variables having a "yrPt" frequency to "last day of the year 12 o'clock noon". The descriptions of some yrPt-variables explicitly state "End of year" and some don't, so this is my best guess. 

I have commited the changes in this branch: https://github.com/EC-Earth/ece2cmor3/tree/fix_issue836
I have tested it for three years (including leap) on all `Eyr` variables for LPJG and it seems to work fine. Let's hope this solves this issue once and for all ;)

**Comment by treerink** [comment]
@nierad the tests were broken in your [fix_issue836](https://github.com/EC-Earth/ece2cmor3/tree/fix_issue836) branch. I have merged the master into this branch, which seems to solve it. Can you update the branch and one time more test if all is fine before we merge it into the master?

**Comment by nierad** [comment]
Hi @treerink, 
I know. I did a `git pull` on the master before I created the branch and it said "up to date with master". Why wasn't that updated?
I rerun the test and the result is OK!

**Comment by treerink** [comment]
@nierad I don't know, sounds like the correct way. Anyway, most important, you fixed the issue. Thanks!

It is merged in the master now.

**Comment by klauswyser** [comment]
Sorry, ``nctxck`` (one of the checks of nctime) still throws errors, e.g.:
````
fracLut_Eyr_EC-Earth3-ESM-1_esm-piControl_r1i1p1f1_gr_1850-1850.nc
        Units:
            IN FILE -- days since 1850-01-01
            REF     -- days since 1850-01-01
        Calendar:
            IN FILE -- proleptic_gregorian
            REF     -- proleptic_gregorian
        Start:
            IN FILE -- 1850 = 1850-12-31T12:00:00 = 364.5
            REF     -- 1850 = 1850-01-01T00:00:00 = 0.0
        End:
            FILENAME -- 1850 = 1850-01-01T00:00:00 = 0.0
            IN FILE  -- 1850 = 1850-12-31T12:00:00 = 364.5
            REBUILT  -- 1850 = 1850-01-01T00:00:00 = 0.0
        Length: 1
        MIP table: Eyr
        Frequency: yrPt = 1 years
        Is instant: True
        Is climatology: False
        Has bounds: False
        Status: Error 001 -- Incorrect time axis over one or several time steps
        Status: Error 010b -- Start date in file is later than start date from filename
        Status: Error 007b -- End date in file is late than end date from filename
        Status: Error 009b -- End date in file is later than theoretical end date
        Wrong time step at index 1: IN FILE -- 1850-12-31T12:00:00 = 364.5      vs. REBUILT -- 1850-01-01T00:00:00 = 0.0       
````
Bounds have been fixed (good!), but for some reason``nctxck`` doesn't like the date at the end of the year and would like to reset it to Jan 1, 00:00:00 of the given year.

However, the [CMIP6 data request for ``fracLut``](https://clipc-services.ceda.ac.uk/dreq/u/d22e4c68-4a9f-11e6-b84e-ac72891c3257.html) clearly states:
````
description[i]: End of year values (not annual mean)
````
and setting the date to Jan 1 doesn't make sense. IMHO ``ntxck`` is simply wrong!

I checked how ``Eyr/fracLut`` is set for example in the AWI model, fracLut_Eyr_AWI-ESM-1-1-LR_piControl_r1i1p1f1_gn_1855-1855.nc. The timestamp is
````
  1855-12-31 23:52:00
````

And when running ``nctxck`` on this file it produces the same error:
````
        Status: Error 001 -- Incorrect time axis over one or several time steps 
        Status: Error 010b -- Start date in file is later than start date from f
ilename 
        Status: Error 007b -- End date in file is late than end date from filena
me 
        Status: Error 009b -- End date in file is later than theoretical end dat
e 
        Wrong time step at index 1: IN FILE -- 1855-12-31T23:52:00 = 59898.99444
444 vs. REBUILT -- 1855-01-01T00:00:00 = 59534.0   
````

My suggestion is that we ignore these ``nctxck`` errors, let the timestep be the end of each year.

If nobody objects I will reprocess the ``Eyr`` variables for the piControl and our member  (r5) of the historical experiments.

**Comment by klauswyser** [comment]
Opened an issue https://github.com/ESPRI-Mod/nctime/issues/6, let's see what happens.

**Comment by nierad** [comment]
My post on [ESPRI-Mod/nctime#6](https://github.com/ESPRI-Mod/nctime/issues/6):
"Maybe it is the time-axis. I used the one given by the drq."
It would be good to know, what `nctxck` actually checks for.

**Comment by klauswyser** [comment]
Yes, the list of datasets in https://github.com/EC-Earth/ece2cmor3/issues/836#issue-2625192076 is still causing troubles with ``nctxck``. Removing time_bnds has removed one error, but the other one about time step being out of the valid range is still there. The problem - as I see it - is that ``nctxck`` thinks the end date of the file should be Jan 1 00Z (see line marked with REF in the log https://github.com/EC-Earth/ece2cmor3/issues/836#issuecomment-2607174158). I don't know why ``nctxck`` makes this assumption, is it from the filename (which is just the year for Eyr files), or is it because of the yrPt frequency that could trick ``nctxck`` to ensure that start_date and end_date are identical. All this is speculation from my side.

Maybe the ``nctxck`` developers respond but not sure, I have the impression that there currently is no active development.

**Comment by nierad** [comment]
I have tried to use YYYY-12-31-24:00:00 but that results in the year being switched to YYYY+1 both in the file and in the filename (and will be beginning of that year, obviously).

**Comment by klauswyser** [comment]
I don't think we should change anything in the time stamp of these files, set it to the last timestep of the year as it says in the CMIP6 data request. IMHO this really is a bug in ``nctxck`` and we just wait until the nctime developers explain why ``nctxck`` throws this error and that it really is an error.

**Comment by treerink** [comment]
Thanks for reporting. I added this issue to the [Know Issues](https://github.com/EC-Earth/ece2cmor3/wiki/Known-issues) wiki.
